apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: green-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: green-frontend
  template:
    metadata:
      labels:
        app: green-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.global.image.registry }}/frontend:{{ .Values.global.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
