root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "./tmp/api"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 500
  kill_delay = "1s"
  rerun_delay = 500

[log]
  time = true

[color]
  build = "green"
  runner = "cyan"
