# Géré par External Secrets Operator — source: HashiCorp Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: green-agent-mtls
  namespace: green-system
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: green-agent-mtls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: k8s-green/agent/mtls
        property: cert
    - secretKey: tls.key
      remoteRef:
        key: k8s-green/agent/mtls
        property: key
    - secretKey: ca.crt
      remoteRef:
        key: k8s-green/agent/mtls
        property: ca
